### ISSUE TITLE
This paper is so intriguing. May I ask you if you plan to open source your code?

### ISSUE THREAD

**Issue by YanhaoZhang** [rkhawad/Object-SLAM#2]

**Comment by YanhaoZhang** [comment]
:smile:

**Comment by rkhawad** [comment]
I am sorry for such a late reply. The work was in collaboration, hence the delay. We will soon share the source code.

**Comment by YanhaoZhang** [comment]
@rkhawad Such a good news. Thank you so much for this reply.
